{% set name = "spsim" %}
{% set version = "1.1.dev" %}
{% set build = 0 %}

{% set cuda_compiler_version = cuda_compiler_version|default('None') %}

{% if cuda_compiler_version == 'None' %}
# prefer no CUDA builds via a build number offset
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_tag: master
  git_url: https://github.com/FXIhub/spsim.git

build:
  number: {{ build }}
  # There are dependency conflicts for Python 2 on Windows
  skip: True  # [win and py<30]
  # There are dependency conflicts for Python 3.8 on Windows
  skip: True  # [win and py>=38]

  # We'll start simple
  skip: True  # [win or osx]
  skip: True  # [py != 37 or cuda_compiler_version != "None"]

requirements:  
  build:
    - git
    - cmake
    - {{ compiler('c') }} # [not osx]
    - {{ compiler('cxx') }} # [not osx]
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != "None"]
  host:
    - cmake
    - python
    - setuptools
    - swig
    - hdf5
    - fftw
    - gsl
    - zlib
    - numpy
    - libspimage 
    - nfft

  run:
    - python
    - hdf5
    - fftw
    - gsl
    - zlib
    - numpy
    - libspimage 
    - nfft

test:
  imports:
    - spsim

about:
  home: https://github.com/FXIhub/spsim
  license: GPL
  license_file: COPYRIGHT
  summary: X-ray single particle diffraction simulator

extra:
  recipe-maintainers: 'FilipeMaia'
